**Pré-requis**

```{r include=FALSE}
install.packages("fUnitRoots")
library(fUnitRoots)
library(MASS)
library(zoo)
```

**Téléchargement puis extraction des données**

```{r}
# Indice CVS-CJO de la production industrielle (base 100 en 2021) - Fabrication de produits explosifs
file_url <- "https://www.insee.fr/fr/statistiques/serie/telecharger/csv/010767819?ordre=antechronologique&transposition=donneescolonne&periodeDebut=1&anneeDebut=1990&periodeFin=2&anneeFin=2024&revision=sansrevisions"
name <- "Fabrication de produits explosifs"

# Indice CVS-CJO de la production industrielle (base 100 en 2021) - Industrie pharmaceutique 
file_url <- "https://www.insee.fr/fr/statistiques/serie/telecharger/csv/010767832?ordre=antechronologique&transposition=donneescolonne&periodeDebut=1&anneeDebut=1990&periodeFin=2&anneeFin=2024&revision=sansrevisions"
name <- "Industrie pharmaceutique"

# Indice CVS-CJO de la production industrielle (base 100 en 2021) - Fabrication de piles et d'accumulateurs électriques
file_url <- "https://www.insee.fr/fr/statistiques/serie/telecharger/csv/010768055?ordre=antechronologique&transposition=donneescolonne&periodeDebut=1&anneeDebut=1990&periodeFin=2&anneeFin=2024&revision=sansrevisions"
name <- "Fabrication de piles et d'accumulateurs électriques"
```


```{r}
local_file_name <- "data.zip"
download.file(file_url, local_file_name, mode = "wb")

file_list <- unzip(local_file_name)
file.rename(file_list[2], "valeurs_mensuelles.csv")

file.remove("data.zip")
file_list[2] <- sub("^\\.\\/", "", file_list[2])
file_list[2] <- sub("/valeurs_mensuelles\\.csv$", "", file_list[2]) 
unlink(file_list[2], recursive = TRUE)

rm(file_url, local_file_name, file_list)
```

**Conversion au format Zoo**

```{r}
data <- read.csv("valeurs_mensuelles.csv", sep = ";")
data <- data[-c(1:3), -3]
colnames(data) <- c("dates", "values")

data <- data[order(data$dates), ]
rownames(data) <- NULL

data$dates <- as.yearmon(data$dates)
data$values <- as.numeric(data$values)

raw_series <- zoo(data$values, order.by=data$dates)
```

# Partie I : données

```{r}
plot(raw_series, main = paste(name, "(undifferenciated)"), xlab = "Date", ylab = "Value")
plot(decompose(raw_series))
```

On observe une double tendance : croissance de la moyenne et de la variance.

```{r}
diff_series <- diff(raw_series, 1)
plot(diff_series, main = paste(name, "(1-differenciated)"), xlab = "Date", ylab = "Value")
```

Une différenciation simple suffit à stationnariser la série.

# Partie II : modèles ARMA

```{r}
acf(diff_series_1, main = paste(name, "(ACF)"))
pacf(diff_series_1, main = paste(name, "(partial ACF)"))
```

# Partie III : Prévision

```{r}

```
